%YAML 1.1
# -*- coding: UTF-8, tab-width: 2 -*-
---

version: '2.2'
services:

  ${dd_tpl_bn}'':
    image: 'node:22'

    command: sh -c 'date -R && sleep 9009009d'
    # ^-- To start an actual debug shell, run:
    #       docker exec --interactive --tty ex01_debug_shell_1 bash -i
    # NB: No "exec" in command: "sleep" seems to ignore SIGTERM when it
    #     runs as pid 1, which would slow down stopping of the container.

    restart: 'always'
    working_dir: '/'
    ports:
      - '127.0.0.1:2322:2322'
      - '127.0.0.1:2370:2370'
      - '127.0.0.1:2380:2380'



...
