%YAML 1.1
# -*- coding: UTF-8, tab-width: 2 -*-
---

version: '2.2'

services:

  ${dd_tpl_bn}'':
    image: 'postgres:14-alpine'
    volumes:
      - ${dd_dir}'@/postgres.data/v14:/pgdata'
      - ${dd_dir}'secrets/postgres.pswd.txt:/run/secrets/postgres/initpswd:ro'
    restart: always
    environment:
      - 'PGDATA=/pgdata'
      # - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD_FILE=/run/secrets/postgres/initpswd'
        #!^# volume_entry_expect_file: -f …
    ports:
      #%sed s!<pg_default_port>!5432!g
      - '127.0.0.1:<pg_default_port>:<pg_default_port>'


...
