%YAML 1.1
# -*- coding: UTF-8, tab-width: 4 -*-
---

version: '3'
services:

  ${DD:tpl_bn}'':
    image: 'python:3-alpine'
    restart: 'no'
    volumes:
      - ${DD:dir}'@/wwwpub:/var/www/pub'
    command: 'python3 -m http.server --directory . 8080'
    working_dir: '/var/www/pub'
    ports:
      - '127.0.0.1:3080:8080'







...
