%YAML 1.1
# -*- coding: UTF-8, tab-width: 4 -*-
---

version: '3'
services:

  ${DD:tpl_bn}'_db':
    image: redis:alpine
    hostname: redisdb
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ${DD:dir}'@/redis.data:/data'
    command: ['redis-server', '--save', '--appendonly', 'yes']

  ${DD:tpl_bn}'_cmdr':
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - 'REDIS_HOSTS=DevDock:redisdb:6379'
    ports:
      - '127.0.0.1:6380:8081'
        # => http://localhost:6380/



...
